import { jsPDF } from "jspdf";

// ─── PALETTE ────────────────────────────────────────────────────────────────
const C = {
  purple:      [108, 43,  217],
  purpleLight: [237, 233, 254],
  pink:        [236,  72, 153],
  cyan:        [  6, 182, 212],
  green:       [ 16, 185, 129],
  amber:       [245, 158,  11],
  slate900:    [ 15,  23,  42],
  slate700:    [ 51,  65,  85],
  slate500:    [100, 116, 139],
  slate200:    [226, 232, 240],
  slate100:    [241, 245, 249],
  white:       [255, 255, 255],
};

const PW       = 210;
const PH       = 297;
const ML       = 20;
const MR       = 20;
const CW       = PW - ML - MR;
const FOOTER_H = 14;
const HEADER_H = 12;

// ─── UTILS ───────────────────────────────────────────────────────────────────
const rgb       = (doc, [r, g, b]) => doc.setTextColor(r, g, b);
const fillRgb   = (doc, [r, g, b]) => doc.setFillColor(r, g, b);
const strokeRgb = (doc, [r, g, b]) => doc.setDrawColor(r, g, b);

function setFont(doc, style = "normal", size = 10) {
  doc.setFontSize(size);
  doc.setFont("helvetica", style);
}

// function swrap(doc, text, maxW) {
//   return doc.splitTextToSize(String(text || ""), maxW);
// }

// ─── HEADER ──────────────────────────────────────────────────────────────────
function drawHeader(doc) {
  fillRgb(doc, C.white);
  doc.rect(0, 0, PW, HEADER_H, "F");
  fillRgb(doc, C.purple);
  doc.rect(0, 0, PW, 1.2, "F");
  strokeRgb(doc, C.slate200);
  doc.setLineWidth(0.3);
  doc.line(ML, HEADER_H, PW - MR, HEADER_H);
  setFont(doc, "bold", 7.5);
  rgb(doc, C.slate500);
  doc.text("MEETMIND AI  -  Meeting Intelligence Report", ML, 8.5);
}

// ─── FOOTER ──────────────────────────────────────────────────────────────────
function drawFooter(doc, pageNum, totalPages) {
  const y = PH - FOOTER_H + 5;
  strokeRgb(doc, C.slate200);
  doc.setLineWidth(0.3);
  doc.line(ML, PH - FOOTER_H, PW - MR, PH - FOOTER_H);
  setFont(doc, "normal", 7.5);
  rgb(doc, C.slate500);
  doc.text("Generated by MEETMIND AI", ML, y);
  const ps = `Page ${pageNum} of ${totalPages}`;
  doc.text(ps, PW - MR - doc.getTextWidth(ps), y);
}

// ─── SECTION TITLE ───────────────────────────────────────────────────────────
// No emoji — plain ASCII text only
function drawSectionTitle(doc, label, y, accentColor = C.purple) {
  fillRgb(doc, accentColor);
  doc.rect(ML, y, 3, 9, "F");
  setFont(doc, "bold", 14);
  rgb(doc, C.slate900);
  doc.text(label, ML + 8, y + 7.5);
  return y + 16;
}

function drawDivider(doc, y) {
  strokeRgb(doc, C.slate200);
  doc.setLineWidth(0.25);
  doc.line(ML, y, PW - MR, y);
  return y + 5;
}

function drawCard(doc, x, y, w, h, fill = C.slate100, r = 3) {
  fillRgb(doc, fill);
  strokeRgb(doc, C.slate200);
  doc.setLineWidth(0.25);
  doc.roundedRect(x, y, w, h, r, r, "FD");
}

// ─── PAGE MANAGER ────────────────────────────────────────────────────────────
class PM {
  constructor(doc) {
    this.doc  = doc;
    this.page = 1;
    this.y    = HEADER_H + 8;
  }
  newPage() {
    this.doc.addPage();
    this.page++;
    this.y = HEADER_H + 8;
    drawHeader(this.doc);
  }
  // Only break if not enough space
  ensure(needed) {
    if (this.y + needed > PH - FOOTER_H - 4) this.newPage();
  }
  get bottom() {
    return PH - FOOTER_H - 4;
  }
}

// ─── COVER PAGE ──────────────────────────────────────────────────────────────
function drawCover(doc, report) {
  // Gradient background top-to-bottom purple → dark
  for (let i = 0; i < 60; i++) {
    const t = i / 60;
    fillRgb(doc, [
      Math.round(C.purple[0] + (C.slate900[0] - C.purple[0]) * t),
      Math.round(C.purple[1] + (C.slate900[1] - C.purple[1]) * t),
      Math.round(C.purple[2] + (C.slate900[2] - C.purple[2]) * t),
    ]);
    doc.rect(0, (PH / 60) * i, PW, PH / 60 + 0.5, "F");
  }

  // Accent lines
  fillRgb(doc, C.pink);
  doc.rect(0, 0, PW, 2, "F");
  fillRgb(doc, C.purple);
  doc.rect(0, PH - 2, PW, 2, "F");

  const cy = 88;

  // Logo box
  fillRgb(doc, [130, 80, 240]);
  doc.roundedRect(PW / 2 - 14, cy - 18, 28, 28, 5, 5, "F");
  setFont(doc, "bold", 18);
  rgb(doc, C.white);
  doc.text("M", PW / 2, cy + 5, { align: "center" });

  // App title
  setFont(doc, "bold", 22);
  rgb(doc, C.white);
  doc.text("MEETMIND AI LEARNING", PW / 2, cy + 26, { align: "center" });

  // Pink divider
  fillRgb(doc, C.pink);
  doc.rect(PW / 2 - 22, cy + 32, 44, 1.5, "F");

  // Report subtitle
  setFont(doc, "bold", 12);
  rgb(doc, [200, 180, 255]);
  doc.text("AI MEETING INTELLIGENCE REPORT", PW / 2, cy + 44, { align: "center" });

  // Session info card
  drawCard(doc, ML + 18, cy + 56, CW - 36, 48, C.white, 4);
  setFont(doc, "bold", 8);
  rgb(doc, C.slate500);
  doc.text("SESSION", PW / 2, cy + 69, { align: "center" });
  setFont(doc, "bold", 11);
  rgb(doc, C.slate900);
  const slines = wrap(doc, report.sessionName || "Meeting Session", CW - 56);
  doc.text(slines[0] || "Meeting Session", PW / 2, cy + 79, { align: "center" });
  setFont(doc, "normal", 8.5);
  rgb(doc, C.slate500);
  doc.text(report.generatedAt || new Date().toLocaleString(), PW / 2, cy + 91, { align: "center" });

  // Powered by
  setFont(doc, "normal", 8);
  rgb(doc, [160, 130, 255]);
  doc.text("Powered by MEETMIND AI", PW / 2, PH - 18, { align: "center" });
}

// ─── STATS DASHBOARD ─────────────────────────────────────────────────────────
// Always starts on page 2. Content after it flows on same page.
function drawStats(doc, pm, report) {
  pm.newPage(); // page 2 always

  let y = pm.y;
  y = drawSectionTitle(doc, "Meeting Overview", y, C.cyan);
  y += 2;

  const stats = [
    { label: "Total\nEntries",  value: report.totalEntries,  color: C.purple   },
    { label: "Mic\nEntries",    value: report.micEntries,    color: C.amber    },
    { label: "System\nEntries", value: report.systemEntries, color: C.cyan     },
    { label: "Total\nWords",    value: report.totalWords,    color: C.slate700  },
    { label: "Mic\nWords",      value: report.micWords,      color: C.amber    },
    { label: "System\nWords",   value: report.systemWords,   color: C.cyan     },
  ];

  const cardW = (CW - 12) / 3;
  const cardH = 34;

  stats.forEach((s, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const cx  = ML + col * (cardW + 6);
    const cy  = y + row * (cardH + 6);

    drawCard(doc, cx, cy, cardW, cardH, C.slate100);
    fillRgb(doc, s.color);
    doc.roundedRect(cx, cy, cardW, 2.5, 1, 1, "F");

    setFont(doc, "bold", 22);
    rgb(doc, s.color);
    doc.text(String(s.value ?? 0), cx + cardW / 2, cy + 18, { align: "center" });

    setFont(doc, "normal", 7.5);
    rgb(doc, C.slate500);
    s.label.split("\n").forEach((ll, li) => {
      doc.text(ll, cx + cardW / 2, cy + 25 + li * 4.5, { align: "center" });
    });
  });

  // Update pm.y to after the 2-row grid, leaving room for next section on same page
  pm.y = y + 2 * (cardH + 6) + 12;
}

// ─── AI SUMMARY ──────────────────────────────────────────────────────────────
// Flows on same page as stats if space, else new page
function drawSummary(doc, pm, report) {
  if (!report.summary) return;

  const PAD_L = 10;
  const PAD_R = 10;
  const textX = ML + PAD_L;
  const wrapW = CW - PAD_L - PAD_R;
  const lines = wrap(doc, report.summary, wrapW);
  const lineH = 6.2;
  const boxH  = lines.length * lineH + 18;

  pm.ensure(20 + boxH + 8);
  let y = pm.y;

  y = drawSectionTitle(doc, "AI Summary", y, C.purple);

  fillRgb(doc, C.purpleLight);
  strokeRgb(doc, C.purple);
  doc.setLineWidth(0.4);
  doc.roundedRect(ML, y, CW, boxH, 4, 4, "FD");
  fillRgb(doc, C.purple);
  doc.rect(ML, y, 3, boxH, "F");

  setFont(doc, "normal", 10);
  rgb(doc, C.slate900);
  lines.forEach((line, i) => doc.text(line, textX, y + 10 + i * lineH));

  pm.y = y + boxH + 10;
}

// ─── KEY POINTS ──────────────────────────────────────────────────────────────
// Flows after summary on same page if space
function drawKeyPoints(doc, pm, report) {
  if (!report.keyPoints?.length) return;

  pm.ensure(20);
  let y = pm.y;
  y = drawSectionTitle(doc, "Key Points", y, C.amber);
  pm.y = y;

  report.keyPoints.forEach((point, i) => {
    const lines = wrap(doc, point, CW - 22);
    const rowH  = lines.length * 6 + 10;

    pm.ensure(rowH + 4);
    y = pm.y;

    if (i % 2 === 0) {
      fillRgb(doc, C.slate100);
      doc.roundedRect(ML, y, CW, rowH, 2, 2, "F");
    }

    // Green bullet circle
    fillRgb(doc, C.green);
    doc.circle(ML + 7, y + rowH / 2, 3.5, "F");
    setFont(doc, "bold", 9);
    rgb(doc, C.white);
    doc.text("+", ML + 5, y + rowH / 2 + 3);

    setFont(doc, "normal", 10);
    rgb(doc, C.slate700);
    lines.forEach((line, li) => doc.text(line, ML + 15, y + 7 + li * 6));

    pm.y += rowH + 4;
  });

  pm.y += 8;
}

// ─── FLASHCARDS ──────────────────────────────────────────────────────────────
function drawFlashcards(doc, pm, report) {
  if (!report.flashcards?.length) return;

  pm.ensure(20);
  let y = pm.y;
  y = drawSectionTitle(doc, "Study Flashcards", y, C.amber);
  pm.y = y;

  report.flashcards.forEach((card, i) => {
    const frontL = wrap(doc, card.front, CW / 2 - 16);
    const backL  = wrap(doc, card.back,  CW / 2 - 16);
    const maxL   = Math.max(frontL.length, backL.length);
    const cardH  = maxL * 6 + 28;

    pm.ensure(cardH + 8);
    y = pm.y;

    const halfW = CW / 2 - 3;

    // FRONT
    drawCard(doc, ML, y, halfW, cardH, C.purpleLight);
    fillRgb(doc, C.purple);
    doc.roundedRect(ML, y, halfW, 2.5, 1, 1, "F");
    setFont(doc, "bold", 7);
    rgb(doc, C.purple);
    doc.text(`CARD ${i + 1}  -  TERM`, ML + 6, y + 10);
    setFont(doc, "bold", 10);
    rgb(doc, C.slate900);
    frontL.forEach((line, li) => doc.text(line, ML + 6, y + 18 + li * 6));

    // BACK
    const bx = ML + halfW + 6;
    drawCard(doc, bx, y, halfW, cardH, [240, 253, 250]);
    fillRgb(doc, C.cyan);
    doc.roundedRect(bx, y, halfW, 2.5, 1, 1, "F");
    setFont(doc, "bold", 7);
    rgb(doc, C.cyan);
    doc.text("DEFINITION", bx + 6, y + 10);
    setFont(doc, "normal", 9.5);
    rgb(doc, C.slate700);
    backL.forEach((line, li) => doc.text(line, bx + 6, y + 18 + li * 6));

    pm.y += cardH + 8;
  });

  pm.y += 8;
}

// ─── QUIZ ────────────────────────────────────────────────────────────────────
function drawQuiz(doc, pm, report) {
  if (!report.quiz?.length) return;

  pm.ensure(20);
  let y = pm.y;
  y = drawSectionTitle(doc, "Knowledge Check", y, C.pink);
  pm.y = y;

  const OPT = ["A", "B", "C", "D"];

  report.quiz.forEach((q, qi) => {
    const qLines = wrap(doc, q.question, CW - 22);
    let totalH   = qLines.length * 6 + 10;
    (q.options || []).forEach(opt => {
      totalH += wrap(doc, opt, CW - 30).length * 5.5 + 6;
    });
    totalH += 12; // correct answer row

    pm.ensure(totalH + 14);
    y = pm.y;

    drawCard(doc, ML, y, CW, totalH + 8, C.slate100);

    // Q badge
    fillRgb(doc, C.pink);
    doc.roundedRect(ML + 4, y + 4, 14, 10, 2, 2, "F");
    setFont(doc, "bold", 8);
    rgb(doc, C.white);
    doc.text(`Q${qi + 1}`, ML + 11, y + 11, { align: "center" });

    setFont(doc, "bold", 10);
    rgb(doc, C.slate900);
    qLines.forEach((line, li) => doc.text(line, ML + 22, y + 9 + li * 6));

    let oy = y + qLines.length * 6 + 14;

    (q.options || []).forEach((opt, oi) => {
      const optL      = wrap(doc, opt, CW - 32);
      const isCorrect = opt === q.answer;
      const rowH      = optL.length * 5.5 + 6;

      if (isCorrect) {
        fillRgb(doc, [220, 252, 231]);
        doc.roundedRect(ML + 8, oy - 2, CW - 16, rowH, 2, 2, "F");
      }

      fillRgb(doc, isCorrect ? C.green : C.slate500);
      doc.circle(ML + 14, oy + rowH / 2 - 2, 3.5, "F");
      setFont(doc, "bold", 7.5);
      rgb(doc, C.white);
      doc.text(OPT[oi], ML + 12.4, oy + rowH / 2 + 1);

      setFont(doc, "normal", 9.5);
      rgb(doc, isCorrect ? C.green : C.slate700);
      optL.forEach((line, li) => doc.text(line, ML + 22, oy + 3.5 + li * 5.5));

      oy += rowH + 2;
    });

    // Correct answer row
    setFont(doc, "bold", 8.5);
    rgb(doc, C.green);
    doc.text(`Correct Answer: ${q.answer}`, ML + 8, oy + 4);

    pm.y += totalH + 18;
  });

  pm.y += 8;
}

// ─── TRANSCRIPT APPENDIX ─────────────────────────────────────────────────────
// Always starts on a fresh page. No emoji — color squares + text labels only.
function drawTranscript(doc, pm, report) {
  pm.newPage();

  let y = pm.y;

  // Appendix label
  setFont(doc, "bold", 9);
  rgb(doc, C.slate500);
  doc.text("APPENDIX A", ML, y);
  y += 7;

  y = drawSectionTitle(doc, "Full Transcript", y, C.slate700);
  y = drawDivider(doc, y);
  pm.y = y;

  // Legend — color squares + text, NO emoji
  pm.ensure(18);
  drawCard(doc, ML, pm.y, CW, 16, C.slate100);

  // Amber square + MIC label
  fillRgb(doc, C.amber);
  doc.roundedRect(ML + 6, pm.y + 5, 8, 6, 1, 1, "F");
  setFont(doc, "bold", 7.5);
  rgb(doc, C.amber);
  doc.text("MIC", ML + 16, pm.y + 10);
  setFont(doc, "normal", 7.5);
  rgb(doc, C.slate500);
  doc.text("= Microphone input", ML + 25, pm.y + 10);

  // Cyan square + SYS label
  fillRgb(doc, C.cyan);
  doc.roundedRect(ML + 88, pm.y + 5, 8, 6, 1, 1, "F");
  setFont(doc, "bold", 7.5);
  rgb(doc, C.cyan);
  doc.text("SYS", ML + 98, pm.y + 10);
  setFont(doc, "normal", 7.5);
  rgb(doc, C.slate500);
  doc.text("= System audio (bold)", ML + 107, pm.y + 10);

  pm.y += 22;

  // Transcript rows
  (report.transcriptBlocks || []).forEach((block, i) => {
    const isMic = block.type === "mic";
    const lines = wrap(doc, block.text || "", CW - 12);
    const rowH  = lines.length * 5.5 + 7;

    pm.ensure(rowH + 2);

    // Alternating row background
    if (i % 2 === 0) {
      fillRgb(doc, [248, 250, 252]);
      doc.rect(ML, pm.y, CW, rowH, "F");
    }

    // Left color bar (amber=mic, cyan=system)
    fillRgb(doc, isMic ? C.amber : C.cyan);
    doc.rect(ML, pm.y, 3, rowH, "F");

    setFont(doc, isMic ? "normal" : "bold", 9);
    rgb(doc, isMic ? C.slate700 : C.slate900);
    lines.forEach((line, li) => {
      doc.text(line, ML + 7, pm.y + 5 + li * 5.5);
    });

    pm.y += rowH + 2;
  });
}

/**
 * Wraps text so that no line exceeds maxWidth.
 * Long words that exceed maxWidth are broken with a soft hyphen (or simply split).
 */
function wrap(doc, text, maxWidth, fontSize = 10) {
  if (!text) return [];
  const words = String(text).split(/\s+/);
  const lines = [];
  let currentLine = "";

  doc.setFontSize(fontSize);
  doc.setFont("helvetica", "normal");

  for (let i = 0; i < words.length; i++) {
    let word = words[i];
    // Check if the word itself is longer than maxWidth
    let wordWidth = doc.getTextWidth(word);
    if (wordWidth > maxWidth) {
      // Break the long word into smaller pieces
      let chars = word.split("");
      let fragment = "";
      for (let ch of chars) {
        let testFragment = fragment + ch;
        if (doc.getTextWidth(testFragment) > maxWidth) {
          if (fragment) {
            // push current fragment as a line (or append to currentLine)
            let candidate = currentLine ? currentLine + fragment : fragment;
            if (doc.getTextWidth(candidate) <= maxWidth) {
              currentLine = candidate;
            } else {
              if (currentLine) lines.push(currentLine.trim());
              currentLine = fragment;
            }
          }
          fragment = ch;
        } else {
          fragment = testFragment;
        }
      }
      if (fragment) {
        let candidate = currentLine ? currentLine + fragment : fragment;
        if (doc.getTextWidth(candidate) <= maxWidth) {
          currentLine = candidate;
        } else {
          if (currentLine) lines.push(currentLine.trim());
          currentLine = fragment;
        }
      }
      continue;
    }

    // Normal word (shorter than maxWidth)
    let testLine = currentLine ? currentLine + " " + word : word;
    if (doc.getTextWidth(testLine) <= maxWidth) {
      currentLine = testLine;
    } else {
      if (currentLine) lines.push(currentLine.trim());
      currentLine = word;
    }
  }
  if (currentLine) lines.push(currentLine.trim());
  return lines;
}
// ─── MAIN EXPORT ─────────────────────────────────────────────────────────────
export function exportPDF(report) {
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });

  // Page 1: Cover (no header/footer)
  drawCover(doc, report);

  const pm = new PM(doc);

  // Page 2: Stats dashboard (forced new page)
  // Summary, Key Points, Flashcards, Quiz flow continuously after — no forced breaks
  drawStats(doc, pm, report);
  drawSummary(doc, pm, report);
  drawKeyPoints(doc, pm, report);
  drawFlashcards(doc, pm, report);
  drawQuiz(doc, pm, report);

  // Appendix: always starts on new page
  drawTranscript(doc, pm, report);

  // Stamp headers + footers on all pages except cover (page 1)
  const total = doc.getNumberOfPages();
  for (let p = 2; p <= total; p++) {
    doc.setPage(p);
    drawFooter(doc, p - 1, total - 1);
  }

  const name = (report.sessionName || "session").replace(/\W+/g, "_");
  doc.save(`MEETMIND_Report_${name}.pdf`);
}